export const COMMODITY_OPTIONS = {
    "001": "General Services",
    "002": "Membership Fees",
    "003": "Workplace Safety",
    "004": "Consulting",
    "005": "Financial Services",
    "006": "Fleet Management",
    "007": "Recruitment Services",
    "008": "Professional Development",
    "009": "Miscellaneous Services",
    "010": "Insurance",
    "011": "Electrical Engineering",
    "012": "Facility Management Services",
    "013": "Security",
    "014": "Renovations",
    "015": "Office Equipment",
    "016": "Energy Management",
    "017": "Maintenance",
    "018": "Cafeteria and Kitchenettes",
    "019": "Cleaning",
    "020": "Audio and Visual Production",
    "021": "Books/Videos/CDs",
    "022": "Printing Costs",
    "023": "Software Development for Publishing",
    "024": "Material Costs",
    "025": "Shipping for Production",
    "026": "Digital Product Development",
    "027": "Pre-production",
    "028": "Post-production Costs",
    "029": "Hardware",
    "030": "IT Services",
    "031": "Software",
    "032": "Courier, Express, and Postal Services",
    "033": "Warehousing and Material Handling",
    "034": "Transportation Logistics",
    "035": "Delivery Services",
    "036": "Advertising",
    "037": "Outdoor Advertising",
    "038": "Marketing Agencies",
    "039": "Direct Mail",
    "040": "Customer Communication",
    "041": "Online Marketing",
    "042": "Events",
    "043": "Promotional Materials",
    "044": "Warehouse and Operational Equipment",
    "045": "Production Machinery",
    "046": "Spare Parts",
    "047": "Internal Transportation",
    "048": "Production Materials",
    "049": "Consumables",
    "050": "Maintenance and Repairs",
};

export const STATUS_COLORS: Record<string, string> = {
    "Open": "bg-blue-100 text-blue-700",
    "In Progress": "bg-yellow-100 text-yellow-700",
    "Closed": "bg-green-100 text-green-700",
};

export const STATUS_OPTIONS = [
    "Open",
    "In Progress",
    "Closed",
];
